version: '3'

services:
  web:
    build: .
    container_name: webapp
    working_dir: /opt/services/web/src/webapp/
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput --clear && gunicorn --chdir webapp --bind :80 webapp.wsgi:application"
    volumes:
      - .:/opt/services/web/src
      - static_volume:/opt/services/web/src/webapp/static
      - media_volume:/opt/services/web/src/webapp/media
    networks:
      - nginx_server
      - db_network
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:1.13
    container_name: nginx_server
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/web/static
      - media_volume:/opt/services/web/media
    depends_on:
      - web
    networks:
      - nginx_server
    # - nginx-proxy
    restart: always
    ports:
      - "8080:80"
    env_file: .env

  db:
    image: postgres:10
    env_file:
      - config/db/db_env
    container_name: db
    networks:
      - db_network
    volumes:
      - db_volume:/var/lib/postgresql/data

networks:
  # Uncomment if using an nginx-proxy image
  # nginx-proxy:
  #   external:
  #      name: nginx-proxy
  nginx_server:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  db_volume:
