version: '3'

services:
    web:
        build: .
        container_name: webapp
        working_dir: /opt/services/web/src/webapp/
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput --clear && gunicorn --chdir webapp --bind :80 webapp.wsgi:application"
        volumes:
            - .:/opt/services/web/src
            - static_volume:/opt/services/web/static
            - media_volume:/opt/services/web/media
        networks:
            - nginx-proxy
            - default_db_network
            - test_db_network
        depends_on:
            - default_db
            - test_db
        restart: always
        expose:
            - "8004"
        env_file: .env

    default_db:
        image: postgres:10
        env_file:
            - config/db/default_db_env
        container_name: default_db
        networks:
            - default_db_network
        volumes:
            - default_db_volume:/var/lib/postgresql/data

    test_db:
        image: postgres:10
        env_file:
            - config/db/test_db_env
        container_name: test_db
        networks:
            - test_db_network
        volumes:
            - test_db_volume:/var/lib/postgresql/data

networks:
    nginx-proxy:
        external:
            name: nginx-proxy
    default_db_network:
        driver: bridge
    test_db_network:
        driver: bridge

volumes:
    default_db_volume:
    test_db_volume:
    static_volume:
    media_volume:
